# gcp-admin-user.yaml
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gcpadminuser
spec:
  profile:
    displayName: GCP Admin
    email: gcpadmin@example.com
    picture: https://example.com/path/to/avatar.jpg  # Optional: URL for the user's avatar
  memberOf: [gcpadmin] # This references the GCPAdmin group, which will be created
