apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gcp-vm-instance
  description: Google Cloud VM used for web services
  namespace: default
spec:
  type: virtual-machine
  owner: team-gcp-owners
  lifecycle: production
  system: your-system
  cloudProvider: gcp
  gce:
    instanceName: idp-backstage
    zone: us-central1-f  # Adjust to your VM's zone
    project: smiling-destiny-429806-g8
  annotations:
    backstage.io/managed-by-location: https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-f/instances/idp-backstage
